
-- 1. FIX ORDERS TABLE
ALTER TABLE IF EXISTS public.orders 
  ADD COLUMN IF NOT EXISTS delivery_otp TEXT,
  ADD COLUMN IF NOT EXISTS otp_verified BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS pickup_address TEXT,
  ADD COLUMN IF NOT EXISTS pickup_lat NUMERIC,
  ADD COLUMN IF NOT EXISTS pickup_lng NUMERIC,
  ADD COLUMN IF NOT EXISTS delivery_address TEXT,
  ADD COLUMN IF NOT EXISTS delivery_lat NUMERIC,
  ADD COLUMN IF NOT EXISTS delivery_lng NUMERIC,
  ADD COLUMN IF NOT EXISTS customer_phone TEXT,
  ADD COLUMN IF NOT EXISTS eta TEXT DEFAULT '25-35 min';

-- 2. FIX RIDER REQUESTS TABLE
ALTER TABLE IF EXISTS public.rider_requests 
  ADD COLUMN IF NOT EXISTS delivery_otp TEXT,
  ADD COLUMN IF NOT EXISTS otp_verified BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS pickup_address TEXT,
  ADD COLUMN IF NOT EXISTS pickup_lat NUMERIC,
  ADD COLUMN IF NOT EXISTS pickup_lng NUMERIC,
  ADD COLUMN IF NOT EXISTS dropoff_address TEXT,
  ADD COLUMN IF NOT EXISTS dropoff_lat NUMERIC,
  ADD COLUMN IF NOT EXISTS dropoff_lng NUMERIC,
  ADD COLUMN IF NOT EXISTS item_description TEXT,
  ADD COLUMN IF NOT EXISTS item_image TEXT,
  ADD COLUMN IF NOT EXISTS total NUMERIC DEFAULT 0;

-- 3. FIX RIDERS TABLE
ALTER TABLE IF EXISTS public.riders 
  ADD COLUMN IF NOT EXISTS rating NUMERIC DEFAULT 4.5,
  ADD COLUMN IF NOT EXISTS total_trips INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vehicle_type TEXT DEFAULT 'Bike',
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;

-- 4. FIX CUSTOMER PROFILES
ALTER TABLE IF EXISTS public.customer_profiles 
  ADD COLUMN IF NOT EXISTS loyalty_points INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS preferred_language TEXT DEFAULT 'en';

-- 5. RELOAD SCHEMA CACHE
NOTIFY pgrst, 'reload schema';

SELECT '✅ SYNC COMPLETE: All frontend-expected columns are now present in the database.' as status;
