// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Production Supabase Configuration - IDENTICAL for Web and Android APK
// These values are safe publishable keys with hardcoded fallbacks to ensure APK works
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://jqbwynomwwjhsebcicpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxYnd5bm9td3dqaHNlYmNpY3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MzUwNDQsImV4cCI6MjA4NjMxMTA0NH0.VMgXx4832iuzP2uLO-YmQ-OHggPLS04nJ2nwHH2nWgY";

// Robust native app detection for Capacitor Android
const detectNativeApp = (): boolean => {
  try {
    if (typeof window === 'undefined') return false;
    const cap = (window as any)?.Capacitor;
    if (!cap) return false;
    const platform = cap?.getPlatform?.();
    return platform === 'android' || platform === 'ios';
  } catch {
    return false;
  }
};

const isNativeApp = detectNativeApp();

// Logging for debugging (development only)
if (import.meta.env.DEV) {
  console.log('[Supabase] Environment:', isNativeApp ? 'Native APK' : 'Web');
  console.log('[Supabase] URL:', SUPABASE_URL);
  console.log('[Supabase] Has env URL:', !!import.meta.env.VITE_SUPABASE_URL);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    // Disable URL detection in native app (no browser URL bar)
    detectSessionInUrl: !isNativeApp,
  },
  global: {
    headers: {
      'X-Client-Info': isNativeApp ? 'fasthaazir-android' : 'fasthaazir-web',
    },
  },
});

// Export configuration for debugging
export const supabaseConfig = {
  url: SUPABASE_URL,
  isNativeApp,
  hasEnvUrl: !!import.meta.env.VITE_SUPABASE_URL,
};
